/* Reserve space for the sdrr_runtime_info structure at start of RAM */
_sdrr_runtime_info_ram = LOADADDR(.sdrr_runtime_info);
.sdrr_runtime_info : AT(_flash_main_firmware_end)
{
    . = ALIGN(4);
    _sdrr_runtime_info_start = .;
    *(.sdrr_runtime_info)
    *(.sdrr_runtime_info*)
    . = _sdrr_runtime_info_start + _Sdrr_Runtime_Info_Size;
    . = ALIGN(4);
    _sdrr_runtime_info_end = .;
} > RAM
