/**
 * A source file generated by MSSP1 I2C host driver.
 *
 * @file mssp1.c
 *
 * @ingroup i2c_host_interrupt
 *
 * @brief This file contains the API implementation for the I2C1 driver.
 *
 * @version I2C1 Driver Version 2.1.3
 * 
 * @version I2C1 Package Version 7.0.4
 */

/*
? [2026] Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms, you may use Microchip 
    software and any derivatives exclusively with Microchip products. 
    You are responsible for complying with 3rd party license terms  
    applicable to your use of 3rd party software (including open source  
    software) that may accompany Microchip software. SOFTWARE IS ?AS IS.? 
    NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS 
    SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT,  
    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT 
    WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY 
    KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF 
    MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE 
    FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP?S 
    TOTAL LIABILITY ON ALL CLAIMS RELATED TO THE SOFTWARE WILL NOT 
    EXCEED AMOUNT OF FEES, IF ANY, YOU PAID DIRECTLY TO MICROCHIP FOR 
    THIS SOFTWARE.
*/

#include <xc.h>
#include "../mssp1.h"

static void I2C1_ReadStart(void);
static void I2C1_WriteStart(void);
static void I2C1_Close(void);
static void I2C1_EventHandler(void);
static void I2C1_ErrorEventHandler(void);

static i2c_host_event_states_t I2C1_EVENT_IDLE(void);
static i2c_host_event_states_t I2C1_EVENT_SEND_RD_ADDR(void);
static i2c_host_event_states_t I2C1_EVENT_SEND_WR_ADDR(void);
static i2c_host_event_states_t I2C1_EVENT_TX(void);
static i2c_host_event_states_t I2C1_EVENT_RX(void);
static i2c_host_event_states_t I2C1_EVENT_NACK(void);
static i2c_host_event_states_t I2C1_EVENT_ERROR(void);
static i2c_host_event_states_t I2C1_EVENT_STOP(void);
static i2c_host_event_states_t I2C1_EVENT_RESET(void);

const i2c_host_interface_t I2C1_Host = {
    .Initialize = I2C1_Initialize,
    .Deinitialize = I2C1_Deinitialize,
    .Write = I2C1_Write,
    .Read = I2C1_Read,
    .WriteRead = I2C1_WriteRead,
    .TransferSetup = NULL,
    .ErrorGet = I2C1_ErrorGet,
    .IsBusy = I2C1_IsBusy,
    .CallbackRegister = I2C1_CallbackRegister,
    .Tasks = NULL
};

static void (*I2C1_Callback)(void) = NULL;
volatile i2c_host_event_status_t i2c1Status = {0};

const i2c1eventHandler i2c1_eventTable[] = {
    I2C1_EVENT_IDLE,
    I2C1_EVENT_SEND_RD_ADDR,
    I2C1_EVENT_SEND_WR_ADDR,
    I2C1_EVENT_TX,
    I2C1_EVENT_RX,
    I2C1_EVENT_NACK,
    I2C1_EVENT_ERROR,
    I2C1_EVENT_STOP,
    I2C1_EVENT_RESET
};

void I2C1_Initialize(void)
{
    /* CKE disabled; SMP Standard Speed;  */
    SSP1STAT = 0x80;
    /* SSPM FOSC/4_SSPxADD_I2C; CKP disabled; SSPEN disabled; SSPOV no_overflow; WCOL no_collision;  */
    SSP1CON1 = 0x8;
    /* SEN disabled; RSEN disabled; PEN disabled; RCEN disabled; ACKEN disabled; ACKDT acknowledge; GCEN disabled;  */
    SSP1CON2 = 0x0;
    /* DHEN disabled; AHEN disabled; SBCDE disabled; SDAHT 100ns; BOEN disabled; SCIE disabled; PCIE disabled;  */
    SSP1CON3 = 0x0;
    /* SSPADD 79;  */
    SSP1ADD = 0x4F;
    PIE3bits.SSP1IE = 1;
    PIE3bits.BCL1IE = 1;
    SSP1CON1bits.SSPEN = 1;
}

void I2C1_Deinitialize(void)
{
    SSP1STAT = 0x00;
    SSP1CON1 = 0x00;
    SSP1CON2 = 0x00;
    SSP1CON3 = 0x00;
    SSP1ADD = 0x00;
    PIE3bits.SSP1IE = 0;
    PIE3bits.BCL1IE = 0;
}

bool I2C1_Write(uint16_t address, uint8_t *data, size_t dataLength)
{
    bool retStatus = false;
    if (!I2C1_IsBusy())
    {
        i2c1Status.busy = true;
        i2c1Status.address = address;
        i2c1Status.switchToRead = false;
        i2c1Status.writePtr = data;
        i2c1Status.writeLength = dataLength;
        i2c1Status.readPtr = NULL;
        i2c1Status.readLength = 0;
        i2c1Status.errorState = I2C_ERROR_NONE;
        I2C1_WriteStart();
        retStatus = true;
    }
    return retStatus;
}

bool I2C1_Read(uint16_t address, uint8_t *data, size_t dataLength)
{
    bool retStatus = false;
    if (!I2C1_IsBusy())
    {
        i2c1Status.busy = true;
        i2c1Status.address = address;
        i2c1Status.switchToRead = false;
        i2c1Status.readPtr = data;
        i2c1Status.readLength = dataLength;
        i2c1Status.writePtr = NULL;
        i2c1Status.writeLength = 0;
        i2c1Status.errorState = I2C_ERROR_NONE;
        I2C1_ReadStart();
        retStatus = true;
    }
    return retStatus;
}

bool I2C1_WriteRead(uint16_t address, uint8_t *writeData, size_t writeLength, uint8_t *readData, size_t readLength)
{
    bool retStatus = false;
    if (!I2C1_IsBusy())
    {
        i2c1Status.busy = true;
        i2c1Status.address = address;
        i2c1Status.switchToRead = true;
        i2c1Status.writePtr = writeData;
        i2c1Status.writeLength = writeLength;
        i2c1Status.readPtr = readData;
        i2c1Status.readLength = readLength;
        i2c1Status.errorState = I2C_ERROR_NONE;
        I2C1_WriteStart();
        retStatus = true;
    }
    return retStatus;
}

i2c_host_error_t I2C1_ErrorGet(void)
{
    i2c_host_error_t retErrorState = i2c1Status.errorState;
    i2c1Status.errorState = I2C_ERROR_NONE;
    return retErrorState;
}

bool I2C1_IsBusy(void)
{
    return i2c1Status.busy;
}

void I2C1_CallbackRegister(void (*callbackHandler)(void))
{
    if (callbackHandler != NULL)
    {
        I2C1_Callback = callbackHandler;
    }
}

void I2C1_ISR(void)
{
    I2C1_EventHandler();
}

void I2C1_ERROR_ISR(void)
{
    I2C1_ErrorEventHandler();
}

/*
 Section: Private Interfaces
 */
static void I2C1_ReadStart(void)
{
    SSP1CON2bits.SEN = 1;
    i2c1Status.state = I2C_STATE_SEND_RD_ADDR;
}

static void I2C1_WriteStart(void)
{
    SSP1CON2bits.SEN = 1;
    i2c1Status.state = I2C_STATE_SEND_WR_ADDR;
}

static void I2C1_Close(void)
{
    i2c1Status.busy = false;
    i2c1Status.address = 0xFF;
    i2c1Status.writePtr = NULL;
    i2c1Status.readPtr = NULL;
    i2c1Status.state = I2C_STATE_IDLE;
    PIR3bits.SSP1IF = 0;
    PIR3bits.BCL1IF = 0;
    SSP1CON1bits.WCOL = 0;
    SSP1CON1bits.SSPOV = 0;
}

static void I2C1_EventHandler(void)
{
    PIR3bits.SSP1IF = 0;
    if (0U != SSP1STATbits.P)
    {
        I2C1_Close();
    }
    else
    {
        if ((SSP1STATbits.D_nA == 0U) && (SSP1CON2bits.ACKSTAT == 1U))
        {
            i2c1Status.state = I2C_STATE_NACK;
            i2c1Status.errorState = I2C_ERROR_ADDR_NACK;
        }
        else if ((SSP1STATbits.D_nA == 1U) && (SSP1CON2bits.ACKSTAT == 1U))
        {
            i2c1Status.state = I2C_STATE_NACK;
            i2c1Status.errorState = I2C_ERROR_DATA_NACK;
        }
        else    
        {        
            // No action required
        }
    }
    
    i2c1Status.state = i2c1_eventTable[i2c1Status.state]();
}

static void I2C1_ErrorEventHandler(void)
{
    i2c1Status.state = I2C_STATE_ERROR;
    i2c1Status.errorState = I2C_ERROR_BUS_COLLISION;
    PIR3bits.BCL1IF = 0;
    i2c1Status.state = i2c1_eventTable[i2c1Status.state]();
    I2C1_Callback();
}

static i2c_host_event_states_t I2C1_EVENT_IDLE(void)
{
    i2c1Status.busy = false;
    return I2C_STATE_RESET;
}

static i2c_host_event_states_t I2C1_EVENT_SEND_RD_ADDR(void)
{
    SSP1BUF = ((uint8_t) ((i2c1Status.address << 1) | 1U));
    return I2C_STATE_RX;
}

static i2c_host_event_states_t I2C1_EVENT_SEND_WR_ADDR(void)
{
    SSP1BUF = ((uint8_t) (i2c1Status.address << 1));
    return I2C_STATE_TX;
}

static i2c_host_event_states_t I2C1_EVENT_TX(void)
{
    i2c_host_event_states_t retEventState = I2C_STATE_TX;
    if (0U != i2c1Status.writeLength)
    {
        i2c1Status.writeLength--;
        SSP1BUF = *i2c1Status.writePtr;
        i2c1Status.writePtr++;
        retEventState = I2C_STATE_TX;
    }
    else
    {
        if (i2c1Status.switchToRead)
        {
            i2c1Status.switchToRead = false;
            SSP1CON2bits.RSEN = 1;
            retEventState = I2C_STATE_SEND_RD_ADDR;
        }
        else
        {
            retEventState = I2C1_EVENT_STOP();
        }
    }

    return retEventState;
}

static i2c_host_event_states_t I2C1_EVENT_RX(void)
{
    i2c_host_event_states_t retEventState = I2C_STATE_RX;

    if (1U == SSP1STATbits.BF)
    {
        if (i2c1Status.readLength > 0U)
        {
            *i2c1Status.readPtr = SSP1BUF;
            i2c1Status.readPtr++;
            i2c1Status.readLength--;

        }

        if (i2c1Status.readLength > 0U)
        {
            SSP1CON2bits.ACKDT = 0;
            SSP1CON2bits.ACKEN = 1;
        }
        else
        {
            SSP1CON2bits.RSEN = 0;
            SSP1CON2bits.ACKDT = 1;
            SSP1CON2bits.ACKEN = 1;
            retEventState = I2C_STATE_STOP;
        }

    }
    else
    {
        SSP1CON2bits.RCEN = 1;
    }
    return retEventState;
}

static i2c_host_event_states_t I2C1_EVENT_NACK(void)
{
    i2c_host_event_states_t retEventState = I2C_STATE_NACK;
    retEventState = I2C1_EVENT_STOP();
    return retEventState;
}

static i2c_host_event_states_t I2C1_EVENT_ERROR(void)
{
    i2c_host_event_states_t retEventState = I2C_STATE_ERROR;
    retEventState = I2C1_EVENT_RESET();
    return retEventState;
}

static i2c_host_event_states_t I2C1_EVENT_STOP(void)
{
    SSP1CON2bits.PEN = 1;
    I2C1_Close();
    return I2C_STATE_IDLE;
}

static i2c_host_event_states_t I2C1_EVENT_RESET(void)
{
    SSP1CON1bits.SSPEN = 0;
    SSP1CON1bits.SSPEN = 1;
    i2c1Status.busy = false;
    return I2C_STATE_IDLE;
}
