// Main header file

// Copyright (C) 2025 Piers Finlayson <piers@piers.rocks>
//
// MIT License

#ifndef SDRR_INCLUDE_H
#define SDRR_INCLUDE_H

#include <stdint.h>
#include <string.h>
#include "SEGGER_RTT.h"

// If you are not using sdrr-gen, you must define configuration options
// manually.  Exmaples are given here:
//
// #define MCU_VARIANT "F103R8"
// #define MCU_FLASH_SIZE 65536
// #define MCO2 1 // Enable MCO2 (microcontroller clock output) on PC9
// #define BOOT_LOGGING 1  // Enable boot logging
// #define DEBUG_LOGGING 1  // Enable more verbose logging
// #define OVERCLOCK 1  // Enable overclocking (may damage the part)
// #define MAIN_LOOP_LOGGING 1  // Enable main loop logging
// #define MAIN_LOOP_ONE_SHOT 1 // Run the main loop once, then log, then run
//                              // it again
// #define DISABLE_CCM 1    // Disable CCM RAM - only relevant for variants
//                          // that support CCM RAM
// #define C_MAIN_LOOP 1    // Disable assembly main loop, use less performant
//                          // C main loop
// #define DUMB_C_MAIN_LOOP_2_CS    // Requires C_MAIN_LOOP, and even worse
//                                  // implementation, which only supports 2
//                                  // CS lines.  Probably don't use.
// #define RP_USE_CP 1  // Use the coprocessor instructions to set the data
//                      // lines as inputs/outputs.  Slight less performant
//                      // than SIO access.
// #define RP_PIO 1     // Use PIO for GPIO access on the RP2350.
//
// sdrr-gen also provides the rom images:
//
// #define SDRR_NUM_IMAGES 1
// const uint8_t sdrr_rom_data[SDRR_NUM_IMAGES][ROM_IMAGE_SIZE] = { ... };

//
// Other supported #defines.
//
// These are provided for testing purposes only as they interefere with the
// normal operation of SDRR and should not be used for production.

//#define TIMER_TEST  5     // Instead of the regular main loop, run a timer
//                          // test, which will log every N seconds.
//#define TOGGLE_PA4  1     // Toggle PA4 as main loop
//#define EXECUTE_FROM_RAM  1   // Whether to execute main loop from RAM (flash
//                              // is the default).  RAM takes nearly twice as
//                              // long to execute, which may seem counter-
//                              // intuitive, but is due to contention on the
//                              // bus used by RAM (and GPIO access).  Flash,
//                              // while it includes wait states, is
//                              // prefetched.

// The main auto-generated SDRR header file - which contains the configuration
// #defines.  Hence it must be loaded before the other stock headers, and
// before the other auto-generated headers.
#include "sdrr_config.h"

// Base configuration header file, included before auto-generated headers.
#include "config_base.h"

// Include the autogenerated SDRR ROMs header file.
#include "roms.h"

// Include the standard SDRR header files 
#include "types.h"
#include "constants.h"
#include "registers.h"
#include "functions.h"

// Main SDRR info struct, defined in sdrr_config.c
extern const sdrr_info_t sdrr_info;

//
// Definition consistency checking
//
#if defined(TIMER_TEST) && defined(TOGGLE_PA4)
#error "TIMER_TEST and EXECUTE_FROM_RAM are mutually exclusive"
#endif // TIMER_TEST/TOGGLE_PA4

#if ((ROM_IMAGE_SIZE * SDRR_NUM_IMAGES) + (16 * 1024)) > MCU_FLASH_SIZE
// Reserving 16KB for SDRR code size
// The linker would throw an error if the image size is too large, but this is
// from graceful.
#error "ROM image size too large for flash"
#endif // ROM image size check

#if defined(TIMER_TEST) && defined(TOGGLE_PA4)
#error "TIMER_TEST and TOGGLE_PA4 are mutually exclusive"
#endif // TIMER_TEST/TOGGLE_PA4

#if defined(MAIN_LOOP_LOGGING) && !defined(BOOT_LOGGING)
#error "MAIN_LOOP_LOGGING requires BOOT_LOGGING to be defined"
#endif // MAIN_LOOP_LOGGING/BOOT_LOGGING

#if defined(DEBUG_LOGGING) && !defined(BOOT_LOGGING)
#error "DEBUG_LOGGING requires BOOT_LOGGING to be defined"
#endif // DEBUG_LOGGING/BOOT_LOGGING

#if !defined(SWD) && defined(RP235X)
#error "SWD being disabled is not supported on RP235X"
#endif // !defined(SWD) && defined(RP235X)

#if defined(MCO) && defined(RP235X)
#error "MCO is not supported on RP235X"
#endif // !defined(SWD) && defined(RP235X)

//
// Set up clocking configuration for the internal and external oscillators
//
// PLL configuration for STM32F4 is auto-generated by sdrr-gen.  Check the
// target frequency is valid.
#if !defined(OVERCLOCK)
#if defined(STM32F401BC) || defined(STM32F401DE)
#if TARGET_FREQ_MHZ > 84
#error "Target frequency for STM32F401 must be 84MHz or less"
#endif // TARGET_FREQ_MHZ > 84
#elif defined(STM32F411)
#if TARGET_FREQ_MHZ > 100
#error "Target frequency for STM32F411 must be 100MHz or less"
#endif // TARGET_FREQ_MHZ > 100
#elif defined(STM32F405)
#if TARGET_FREQ_MHZ > 168
#error "Target frequency for STM32F405 must be 168MHz or less"
#endif // TARGET_FREQ_MHZ > 168
#elif defined(STM32F446)
#if TARGET_FREQ_MHZ > 180
#error "Target frequency for STM32F446 must be 180MHz or less"
#endif // TARGET_FREQ_MHZ > 180
#endif // STM32F4xx
#endif // !OVERCLOCK

//
// Set up debug logging
//
#if defined(BOOT_LOGGING)
#define LOG_INIT()   log_init()
#define LOG(X, ...)  do_log(X, ##__VA_ARGS__)
#else // BOOT_LOGGING
#define LOG_INIT()
#define LOG(X, ...)
#endif // BOOT_LOGGING
#if defined(DEBUG_LOGGING)
#define DEBUG(X, ...)  do_log(X, ##__VA_ARGS__)
#else // DEBUG_LOGGING
#define DEBUG(X, ...)
#endif // DEBUG_LOGGING

#define BOOTLOADER_SEL_MASK  0b10000111

// Struct used to hold the runtime information for SDRR
extern sdrr_runtime_info_t sdrr_runtime_info;

// Linker variables, used by log_init()
extern uint32_t _flash_start;
extern uint32_t _flash_end;
extern uint32_t _ram_size;

#if defined(STM32F4)
#include "stm32f4_inlines.h"
#endif // STM32F4

#if defined(RP235X)
#include "rp235x_inlines.h"
#endif // RP235X

#endif // SDRR_INCLUDE_H
